services:
  - type: web
    name: football-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn proxy_apifootball:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_FOOTBALL_KEY
        sync: false
